const inspirationalClasses = [
    {
        "image":"/images/InspirationalClasses_3.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Ayesha Amjad",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_2.jpg",
        "description": "Become a Certified Web Designer & Developer",
        "name": "Asim Manzoor",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_1.jpg",
        "description": "Become a Certified Full Stack Web Developer",
        "name": "Faisal Javeed",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_4.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Aqsa Razzaq",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_3.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Ayesha Amjad",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_2.jpg",
        "description": "Become a Certified Web Designer & Developer",
        "name": "Asim Manzoor",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_1.jpg",
        "description": "Become a Certified Full Stack Web Developer",
        "name": "Faisal Javeed",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_4.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Aqsa Razzaq",
        "category": "Featured",
    },
    {
        "image":"/images/InspirationalClasses_2.jpg",
        "description": "Become a Certified Web Designer & Developer",
        "name": "Asim Manzoor",
        "category": "Development",
    },
    {
        "image":"/images/InspirationalClasses_1.jpg",
        "description": "Become a Certified Full Stack Web Developer",
        "name": "Faisal Javeed",
        "category": "Marketing",
    },
    {
        "image":"/images/InspirationalClasses_4.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Aqsa Razzaq",
        "category": "Design",
    },
    {
        "image":"/images/InspirationalClasses_3.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Ayesha Amjad",
        "category": "Business",
    },
    {
        "image":"/images/InspirationalClasses_2.jpg",
        "description": "Become a Certified Web Designer & Developer",
        "name": "Asim Manzoor",
        "category": "Accounts",
    },
    {
        "image":"/images/InspirationalClasses_1.jpg",
        "description": "Become a Certified Full Stack Web Developer",
        "name": "Faisal Javeed",
        "category": "Photography",
    },
    {
        "image":"/images/InspirationalClasses_4.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Aqsa Razzaq",
        "category": "Acting",
    },
    {
        "image":"/images/InspirationalClasses_3.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Ayesha Amjad",
        "category": "Multimedia",
    },
    {
        "image":"/images/InspirationalClasses_2.jpg",
        "description": "Become a Certified Web Designer & Developer",
        "name": "Asim Manzoor",
        "category": "IT Softwares",
    },
    {
        "image":"/images/InspirationalClasses_1.jpg",
        "description": "Become a Certified Full Stack Web Developer",
        "name": "Faisal Javeed",
        "category": "Sewing",
    },
    {
        "image":"/images/InspirationalClasses_4.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Aqsa Razzaq",
        "category": "SEO",
    },
    {
        "image":"/images/InspirationalClasses_1.jpg",
        "description": "Become a Certified Full Stack Web Developer",
        "name": "Faisal Javeed",
        "category": "React JS",
    },
    {
        "image":"/images/InspirationalClasses_4.jpg",
        "description": "Certified Digital Media Marketing (CDMM) Expert Course (06 Months)",
        "name": "Aqsa Razzaq",
        "category": "Node JS",
    },

]
export default inspirationalClasses